In [92]:
import spacy

from spacy.lang.en.stop_words import STOP_WORDS

len(STOP_WORDS)

327

In [93]:
STOP_WORDS # A set of stop words in spaCy

{"'d",
 "'ll",
 "'m",
 "'re",
 "'s",
 "'ve",
 'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'both',
 'bottom',
 'btw',
 'but',
 'by',
 'ca',
 'call',
 'can',
 'cannot',
 'could',
 'did',
 'do',
 'does',
 'doing',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fifty',
 'first',
 'five',
 'for',
 'former',
 'formerly',
 'forty',
 'four',
 'from',
 'front',
 'full',
 'further',
 'get',
 'give',
 'go',
 'had',
 'has',
 'have',
 'he',
 'hence',
 'her',
 'here',
 'hereafter',
 'hereby',
 'herein',
 'hereupon',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'however',
 'hundred',
 'i',
 'if',
 'in',
 'indeed',
 'into',
 'is',
 'it',
 'its',
 'itself',
 'just',
 'keep',
 'last',
 'latter',
 'latterly',
 'least',
 'less',
 'made',
 'make',
 'many',
 'may',
 'me',
 'meanwhile',
 'might',
 'mine',
 'more',
 'moreover',
 'most',
 'mostly',
 'move',
 'much',
 'must',
 'my',
 'myself',
 "n't",
 'name',
 'namely',
 'neither',
 'never',
 'nevertheless',
 'next',
 'nine',
 'no',
 'nobody',
 'none',
 'noone',
 'nor',
 'not',
 'nothing',
 'now',
 'nowhere',
 'n‘t',
 'n’t',
 'of',
 'off',
 'often',
 'on',
 'once',
 'one',
 'only',
 'onto',
 'or',
 'other',
 'others',
 'otherwise',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'part',
 'per',
 'perhaps',
 'please',
 'put',
 'quite',
 'rather',
 're',
 'really',
 'regarding',
 'same',
 'say',
 'see',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'serious',
 'several',
 'she',
 'should',
 'show',
 'side',
 'since',
 'six',
 'sixty',
 'so',
 'some',
 'somehow',
 'someone',
 'something',
 'sometime',
 'sometimes',
 'somewhere',
 'still',
 'such',
 'take',
 'ten',
 'than',
 'that',
 'the',
 'their',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 'thereafter',
 'thereby',
 'therefore',
 'therein',
 'thereupon',
 'these',
 'they',
 'third',
 'this',
 'those',
 'though',
 'three',
 'through',
 'throughout',
 'thru',
 'thus',
 'to',
 'together',
 'too',
 'top',
 'toward',
 'towards',
 'twelve',
 'twenty',
 'two',
 'under',
 'unless',
 'until',
 'up',
 'upon',
 'us',
 'used',
 'using',
 'various',
 'very',
 'via',
 'was',
 'we',
 'well',
 'were',
 'what',
 'whatever',
 'when',
 'whence',
 'whenever',
 'where',
 'whereafter',
 'whereas',
 'whereby',
 'wherein',
 'whereupon',
 'wherever',
 'whether',
 'which',
 'while',
 'whither',
 'who',
 'whoever',
 'whole',
 'whom',
 'whose',
 'why',
 'will',
 'with',
 'within',
 'without',
 'would',
 'yet',
 'you',
 'your',
 'yours',
 'yourself',
 'yourselves',
 '‘d',
 '‘ll',
 '‘m',
 '‘re',
 '‘s',
 '‘ve',
 '’d',
 '’ll',
 '’m',
 '’re',
 '’s',
 '’ve'}

In [94]:
STOP_WORDS.add("btw")  # Adding a new stop word
"btw" in STOP_WORDS

True

In [95]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("We just opened our wings, the flying part is coming soon")

for token in doc:
    if token.is_stop:
        print(token)

We
just
our
the
part
is

In [96]:
# Preprocessing function to remove stop words from text
def preprocess(text):
    doc = nlp(text)
    # List comprehension to filter out stop words, here token.is_stop is used to check if the token is a stop word
    no_stop_words = [token.text for token in doc if not token.is_stop]  # if token is not a stop word then enter inside loop and add to list.
    return " ".join(no_stop_words) # Join the list of words back into a single string

In [97]:
preprocess("Musk wants time to prepare for a trial over his")

'Musk wants time prepare trial'

In [98]:
def preprocess(text):
    doc = nlp(text)
    # List comprehension to filter out stop words, here token.is_stop is used to check if the token is a stop word
    no_stop_words = [token.text for token in doc if not token.is_stop and not token.is_punct]  # if token is not a stop word and not punctuation then enter inside loop and add to list.
    return no_stop_words

In [99]:
preprocess("The other is? not other but! your, divine brother")

['divine', 'brother']

In [100]:
# Remove stop words from pandas dataframe text column

In [101]:
# Dataset contains press releases of different court cases from depart of justice (DOJ).
# The releases contain information such as outcomes of criminal cases, notable actions taken against felons, or other updates about the current administration.

In [102]:
import pandas as pd

df = pd.read_json("doj_press.json",lines=True) # here lines=True indicates that each line of the file is a separate JSON object.

df.shape

(13087, 6)

In [103]:
df.head(5)

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [104]:
# above dataset have null values in topics column.
# Filter out those rows that do not have any topics associated with the case

In [105]:
df = df[df["topics"].str.len() != 0] # keep only those rows where length of topics column is not equal to zero.
df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [106]:
df.shape # after removing rows with null topics shape has changed.

(4688, 6)

In [107]:
df =df.head(100) # for demonstration purpose taking only first 100 rows.
df.shape

(100, 6)

In [108]:
df.head(2)

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]

In [109]:
df["contents_new"] = df.contents.apply(preprocess) # here preprocess function filters out stop words from contents column and creates a new column contents_new.

In [110]:
df

,id,title,contents,date,topics,components,contents_new
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],"[U.S., Department, Justice, U.S., Environmenta..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],"[131, count, criminal, indictment, unsealed, t..."
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...","[United, States, Attorney, Office, Middle, Dis..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],"[21st, Century, Oncology, LLC, agreed, pay, $,..."
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]","[21st, Century, Oncology, Inc., certain, subsi..."
...,...,...,...,...,...,...,...
316,15-1359,Alaska Plastic Surgeon Convicted of Wire Fraud...,Doctor Hid Millions in Secret Accounts in Pana...,2015-11-04T00:00:00-05:00,[Tax],[Tax Division],"[Doctor, Hid, Millions, Secret, Accounts, Pana..."
318,16-396,Alaska Plastic Surgeon Sentenced to Prison for...,Defendant Concealed Bank Accounts in Panama an...,2016-04-04T00:00:00-04:00,[Tax],[Tax Division],"[Defendant, Concealed, Bank, Accounts, Panama,..."
321,17-736,Alaskan Commercial Fishing Couple Charged with...,An Alaskan couple was charged in federal court...,2017-07-26T00:00:00-04:00,[Tax],"[Tax Division, USAO - Alaska]","[Alaskan, couple, charged, federal, court, Jun..."
322,18-717,Alaskan Husband And Wife Plead Guilty To Willf...,A husband and wife pleaded guilty yesterday to...,2018-06-01T00:00:00-04:00,[Tax],[Tax Division],"[husband, wife, pleaded, guilty, yesterday, co..."
324,16-1345,Alaskan Oncologist Indicted for Tax Evasion,"A resident of Big Lake, Alaska was indicted on...",2016-11-17T00:00:00-05:00,[Tax],[Tax Division],"[resident, Big, Lake, Alaska, indicted, counts..."

In [111]:
len(df.contents[4]) # length of original contents column

6286

In [ ]:
len(df.contents_new[4]) # length of contents_new column after removing stop words

565

In [ ]:
df.contents[4][:300]

'The U.S. Department of Justice, the U.S. Environmental Protection Agency (EPA), and the Rhode Island Department of Environmental Management (RIDEM) announced today that two subsidiaries of Stanley Black & Decker Inc.—Emhart Industries Inc. and Black & Decker Inc.—have agreed to clean up dioxin conta'

In [ ]:
df.contents_new[4][:300] # first 300 characters of contents_new column after removing stop words

['U.S.',
 'Department',
 'Justice',
 'U.S.',
 'Environmental',
 'Protection',
 'Agency',
 'EPA',
 'Rhode',
 'Island',
 'Department',
 'Environmental',
 'Management',
 'RIDEM',
 'announced',
 'today',
 'subsidiaries',
 'Stanley',
 'Black',
 'Decker',
 'Inc.—Emhart',
 'Industries',
 'Inc.',
 'Black',
 'Decker',
 'Inc.—have',
 'agreed',
 'clean',
 'dioxin',
 'contaminated',
 'sediment',
 'soil',
 'Centredale',
 'Manor',
 'Restoration',
 'Project',
 'Superfund',
 'Site',
 'North',
 'Providence',
 'Johnston',
 'Rhode',
 'Island',
 '\xa0 ',
 'pleased',
 'reach',
 'resolution',
 'collaborative',
 'work',
 'responsible',
 'parties',
 'EPA',
 'stakeholders',
 'said',
 '\xa0',
 'Acting',
 'Assistant',
 'Attorney',
 'General',
 'Jeffrey',
 'H.',
 'Wood',
 'Justice',
 'Department',
 '\xa0',
 'Environment',
 'Natural',
 'Resources',
 'Division',
 'Today',
 'settlement',
 'ends',
 'protracted',
 'litigation',
 'allows',
 'important',
 'work',
 'underway',
 'restore',
 'healthy',
 'environment',
 'citizens',
 'living',
 'Centredale',
 'Manor',
 'Site',
 'Woonasquatucket',
 'River',
 'settlement',
 'demonstrates',
 'tremendous',
 'progress',
 'achieving',
 'working',
 'responsible',
 'parties',
 'states',
 'federal',
 'partners',
 'expedite',
 'sites',
 'entire',
 'Superfund',
 'remediation',
 'process',
 'said',
 'EPA',
 'Acting',
 'Administrator',
 'Andrew',
 'Wheeler',
 'Centredale',
 'Manor',
 'Site',
 'National',
 'Priorities',
 'List',
 '18',
 'years',
 'taking',
 'charge',
 'ensuring',
 'Agency',
 'makes',
 'good',
 'promise',
 'clean',
 'betterment',
 'environment',
 'communities',
 'affected',
 'Successfully',
 'concluding',
 'settlement',
 'paves',
 'way',
 'EPA',
 'good',
 'commitment',
 'aggressively',
 'pursue',
 'cleaning',
 'Centredale',
 'Manor',
 'Superfund',
 'Site',
 'said',
 'EPA',
 'New',
 'England',
 'Regional',
 'Administrator',
 'Alexandra',
 'Dunn',
 'excited',
 'work',
 'cleanup',
 'site',
 'closer',
 'goal',
 'fully',
 'utilized',
 'North',
 'Providence',
 'Johnston',
 'communities',
 'pleased',
 'collective',
 'efforts',
 'State',
 'Rhode',
 'Island',
 'EPA',
 'DOJ',
 'negotiations',
 'concluded',
 'major',
 'milestone',
 'cleanup',
 'Centredale',
 'Manor',
 'Restoration',
 'Superfund',
 'site',
 'consistent',
 'long',
 'standing',
 'efforts',
 'polluter',
 'pay',
 'said',
 'RIDEM',
 'Director',
 'Janet',
 'Coit',
 'settlement',
 'speed',
 'remedy',
 'protects',
 'public',
 'health',
 'river',
 'environment',
 'moves',
 'closer',
 'day',
 'reclaim',
 'recreational',
 'uses',
 'beautiful',
 'river',
 'resource',
 'settlement',
 'includes',
 'cleanup',
 'work',
 'Woonasquatucket',
 'River',
 'River',
 'bordering',
 'residential',
 'commercial',
 'properties',
 'River',
 'requires',
 'companies',
 'perform',
 'remedy',
 'selected',
 'EPA',
 'Site',
 '2012',
 'estimated',
 'cost',
 'approximately',
 '$',
 '100',
 'million',
 'resolves',
 'longstanding',
 'litigation',
 'cleanup',
 'remedy',
 'includes',
 'excavation',
 'contaminated',
 'sediment',
 'floodplain',
 'soil',
 'Woonasquatucket',
 'River',
 'including',
 'adjacent',
 'residential',
 'properties',
 'cleanup',
 'remedy',
 'completed',
 'access',
 'Woonasquatucket',
 'River',
 'restored',
 'local',
 'citizens',
 'cleanup',
 'step',
 'State',
 'goal',
 'fishable',
 'swimmable',
 'river',
 'work',
 'include',
 'upgrading',
 'caps',
 'contaminated',
 'soil',
 'peninsula',
 'area',
 'Site',
 'currently',
 'house',
 'high',
 'rise',
 'apartment',
 'buildings',
 'settlement',
 'ensures',
 'long',
 'term',
 'monitoring',
 'maintenance',
 'site',
 'directed',
 'remedy',
 'implemented',
 'ensure',
 'public',
 'health',
 'protected']

In [115]:
# Examples where removing stop words can create a problem

In [116]:
#(1) Sentiment detection: Not always but in some cases, based on 
# your dataset it can change the sentiment of a sentence if you remove stop words

In [117]:
preprocess("this is a good movie")

['good', 'movie']

In [118]:
preprocess("this is not a good movie")

['good', 'movie']

In [119]:
# (2) Language translation: Say you want to translate following sentence from english to telugu. 
# Before actual translation if you remove stop words and then translate, it will produce horrible result

In [120]:
preprocess("how are you doing dhaval?")

['dhaval']

In [121]:
# (3) Chat bot or any Q&A system

In [122]:
preprocess("I don't find yoga mat on your website. Can you help?")

['find', 'yoga', 'mat', 'website', 'help']